// African countries with their first-level regions, and a list of languages spoken across
// Africa. Generated from the `country-region-data` package (MIT), trimmed to the 54
// African countries. Some countries have since changed their divisions, so the form also
// offers "Other".

export type Country = { code: string, name: string, regions: string[] }
export type Language = { code: string, name: string }

export const AFRICAN_COUNTRIES: Country[] = [
  {"code": "DZ", "name": "Algeria", "regions": ["Adrar", "Algiers", "Annaba", "Aïn Defla", "Aïn Témouchent", "Batna", "Biskra", "Blida", "Bordj Bou Arréridj", "Boumerdès", "Bouïra", "Béchar", "Béjaïa", "Chlef", "Constantine", "Djelfa", "El Bayadh", "El Oued", "El Tarf", "Ghardaïa", "Guelma", "Illizi", "Jijel", "Khenchela", "Laghouat", "Mascara", "Mila", "Mostaganem", "Msila", "Médéa", "Naâma", "Oran", "Ouargla", "Oum el Bouaghi", "Relizane", "Saïda", "Sidi Bel Abbès", "Skikda", "Souk Ahras", "Sétif", "Tamanghasset", "Tiaret", "Tindouf", "Tipaza", "Tissemsilt", "Tizi Ouzou", "Tlemcen", "Tébessa"]},
  {"code": "AO", "name": "Angola", "regions": ["Bengo", "Benguela", "Bié", "Cabinda", "Cuando Cubango", "Cuanza Norte", "Cuanza Sul", "Cunene", "Huambo", "Huíla", "Luanda", "Lunda Norte", "Lunda Sul", "Malanje", "Moxico", "Namibe", "Uíge", "Zaire"]},
  {"code": "BJ", "name": "Benin", "regions": ["Alibori", "Atakora", "Atlantique", "Borgou", "Collines Department", "Donga", "Kouffo", "Littoral Department", "Mono Department", "Ouémé", "Plateau", "Zou"]},
  {"code": "BW", "name": "Botswana", "regions": ["Central", "Ghanzi", "Kgalagadi", "Kgatleng", "Kweneng", "North West", "North-East", "South East", "Southern"]},
  {"code": "BF", "name": "Burkina Faso", "regions": ["Balé", "Bam/Lake Bam", "Banwa Province", "Bazèga", "Bougouriba", "Boulgou Province", "Boulkiemdé", "Comoé/Komoe", "Ganzourgou Province", "Gnagna", "Gourma Province", "Houet", "Ioba", "Kadiogo", "Komondjari", "Kompienga", "Kossi Province", "Koulpélogo", "Kouritenga", "Kourwéogo", "Kénédougou", "Loroum", "Léraba", "Mouhoun", "Namentenga", "Naouri/Nahouri", "Nayala", "Noumbiel", "Oubritenga", "Oudalan", "Passoré", "Poni", "Sanguié", "Sanmatenga", "Sissili", "Soum", "Sourou", "Séno", "Tapoa", "Tui/Tuy", "Yagha", "Yatenga", "Ziro", "Zondoma", "Zoundwéogo"]},
  {"code": "BI", "name": "Burundi", "regions": ["Bubanza", "Bujumbura Mairie", "Bujumbura Rural", "Bururi", "Cankuzo", "Cibitoke", "Gitega", "Karuzi", "Kayanza", "Kirundo", "Makamba", "Muramvya", "Muyinga", "Mwaro", "Ngozi", "Rutana", "Ruyigi"]},
  {"code": "CV", "name": "Cabo Verde", "regions": ["Boa Vista", "Brava", "Calheta de São Miguel", "Maio", "Mosteiros", "Paúl", "Porto Novo", "Praia", "Ribeira Brava", "Ribeira Grande", "Sal", "Santa Catarina", "Santa Cruz", "São Domingos", "São Filipe", "São Nicolau", "São Vicente", "Tarrafal", "Tarrafal de São Nicolau"]},
  {"code": "CM", "name": "Cameroon", "regions": ["Adamaoua", "Centre", "Est", "Extrême-Nord", "Littoral", "Nord", "Nord-Ouest", "Ouest", "Sud", "Sud-Ouest"]},
  {"code": "CF", "name": "Central African Republic", "regions": ["Bamingui-Bangoran", "Bangui", "Basse-Kotto", "Haut-Mbomou", "Haute-Kotto", "Kémo", "Lobaye", "Mambéré-Kadéï", "Mbomou", "Nana-Grebizi", "Nana-Mambéré", "Ombella-M'Poko", "Ouaka", "Ouham", "Ouham Péndé", "Sangha-Mbaéré", "Vakaga"]},
  {"code": "TD", "name": "Chad", "regions": ["Bahr el Ghazal", "Batha", "Borkou", "Chari-Baguirmi", "Ennedi-Est", "Ennedi-Ouest", "Guéra", "Hadjer Lamis", "Kanem", "Lac", "Logone Occidental", "Logone Oriental", "Mayo-Kébbi-Est", "Mondoul", "Moyen-Chari", "Ouaddai", "Salamat", "Sila", "Tandjilé", "Tibesti", "Ville de Ndjamena", "Wadi Fira"]},
  {"code": "KM", "name": "Comoros", "regions": ["Andjazîdja", "Andjouân", "Moûhîlî"]},
  {"code": "CI", "name": "Côte d'Ivoire", "regions": ["Agnéby", "Bafing", "Bas-Sassandra", "Denguélé", "Dix-Huit Montagnes", "Fromager", "Haut-Sassandra", "Lacs", "Lagunes", "Marahoué", "Moyen-Cavally", "Moyen-Comoé", "N'zi-Comoé", "Savanes", "Sud-Bandama", "Sud-Comoé", "Vallée du Bandama", "Worodougou", "Zanzan"]},
  {"code": "CD", "name": "DR Congo", "regions": ["Bandundu", "Bas-Congo", "Kasaï-Occidental", "Kasaï-Oriental", "Katanga", "Kinshasa", "Maniema", "Nord-Kivu", "Orientale", "Sud-Kivu", "Équateur"]},
  {"code": "DJ", "name": "Djibouti", "regions": ["Ali Sabieh", "Arta", "Dikhil", "Obock", "Tadjourah"]},
  {"code": "EG", "name": "Egypt", "regions": ["Alexandria", "Aswan", "Asyout", "Bani Sueif", "Beheira", "Cairo", "Daqahlia", "Dumiat", "El Bahr El Ahmar", "El Ismailia", "El Suez", "El Wadi El Gedeed", "Fayoum", "Gharbia", "Giza", "Helwan", "Kafr El Sheikh", "Luxor", "Matrouh", "Menia", "Menofia", "North Sinai", "Port Said", "Qalubia", "Qena", "Sharqia", "Sixth of October", "Sohag", "South Sinai"]},
  {"code": "GQ", "name": "Equatorial Guinea", "regions": ["Annobón", "Bioko Norte", "Bioko Sur", "Centro Sur", "Kié-Ntem", "Litoral", "Wele-Nzas"]},
  {"code": "ER", "name": "Eritrea", "regions": ["Anseba", "Debub", "Debub-Keih-Bahri", "Gash-Barka", "Maekel", "Semien-Keih-Bahri"]},
  {"code": "SZ", "name": "Eswatini", "regions": ["Hhohho", "Lubombo", "Manzini", "Shiselweni"]},
  {"code": "ET", "name": "Ethiopia", "regions": ["Addis Ababa", "Afar", "Amhara", "Benshangul-Gumaz", "Dire Dawa", "Gambela", "Harari", "Oromia", "Somali", "Southern Nations Nationalities and People's Region", "Tigray"]},
  {"code": "GA", "name": "Gabon", "regions": ["Estuaire", "Haut-Ogooué", "Moyen-Ogooué", "Ngounié", "Nyanga", "Ogooué-Ivindo", "Ogooué-Lolo", "Ogooué-Maritime", "Woleu-Ntem"]},
  {"code": "GH", "name": "Ghana", "regions": ["Ahafo", "Ashanti", "Bono", "Bono East", "Central", "Eastern", "Greater Accra", "North East", "Northern", "Oti", "Savannah", "Upper East", "Upper West", "Volta", "Western", "Western North"]},
  {"code": "GN", "name": "Guinea", "regions": ["Boké", "Conakry", "Faranah", "Kankan", "Kindia", "Labé", "Mamou", "Nzérékoré"]},
  {"code": "GW", "name": "Guinea-Bissau", "regions": ["Bafatá", "Biombo", "Bissau", "Bolama-Bijagos", "Cacheu", "Gabú", "Oio", "Quinara", "Tombali"]},
  {"code": "KE", "name": "Kenya", "regions": ["Baringo", "Bomet", "Bungoma", "Busia", "Eleyo/Marakwet", "Embu", "Garissa", "Homa Bay", "Isiolo", "Kajiado", "Kakamega", "Kericho", "Kiambu", "Kilifi", "Kirinyaga", "Kisii", "Kisumu", "Kitui", "Kwale", "Laikipia", "Lamu", "Machakos", "Makueni", "Mandera", "Marsabit", "Meru", "Migori", "Mombasa", "Murang'a", "Nairobi City", "Nakuru", "Nandi", "Narok", "Nyamira", "Nyandarua", "Nyeri", "Samburu", "Siaya", "Taita/Taveta", "Tana River", "Tharaka-Nithi", "Trans Nzoia", "Turkana", "Uasin Gishu", "Vihiga", "Wajir", "West Pokot"]},
  {"code": "LS", "name": "Lesotho", "regions": ["Berea", "Butha-Buthe", "Leribe", "Mafeteng", "Maseru", "Mohales Hoek", "Mokhotlong", "Qacha's Nek", "Quthing", "Thaba-Tseka"]},
  {"code": "LR", "name": "Liberia", "regions": ["Bomi", "Bong", "Gbarpolu", "Grand Bassa", "Grand Cape Mount", "Grand Gedeh", "Grand Kru", "Lofa", "Margibi", "Maryland", "Montserrado", "Nimba", "River Cess", "River Geee", "Sinoe"]},
  {"code": "LY", "name": "Libya", "regions": ["Al Buţnān", "Al Jabal al Akhḑar", "Al Jabal al Gharbī", "Al Jafārah", "Al Jufrah", "Al Kufrah", "Al Marj", "Al Marquab", "Al Wāḩāt", "An Nuqaţ al Khams", "Az Zāwiyah", "Banghāzī", "Darnah", "Ghāt", "Mişrātah", "Murzuq", "Nālūt", "Sabhā", "Surt", "Wādī ash Shāţiʾ", "Yafran", "Ţarābulus"]},
  {"code": "MG", "name": "Madagascar", "regions": ["Antananarivo", "Antsiranana", "Fianarantsoa", "Mahajanga", "Toamasina", "Toliara"]},
  {"code": "MW", "name": "Malawi", "regions": ["Balaka", "Blantyre", "Chikwawa", "Chiradzulu", "Chitipa", "Dedza", "Dowa", "Karonga", "Kasungu", "Likoma", "Lilongwe", "Machinga", "Mangochi", "Mchinji", "Mulanje", "Mwanza", "Mzimba", "Nkhata Bay", "Nkhotakota", "Nsanje", "Ntcheu", "Ntchisi", "Phalombe", "Rumphi", "Salima", "Thyolo", "Zomba"]},
  {"code": "ML", "name": "Mali", "regions": ["Bamako", "Gao", "Kayes", "Kidal", "Koulikoro", "Mopti", "Ménaka", "Segou", "Sikasso", "Taoudénit", "Tombouctou"]},
  {"code": "MR", "name": "Mauritania", "regions": ["Adrar", "Assaba", "Brakna", "Dakhlet Nouadhibou", "Gorgol", "Guidimaka", "Hodh Ech Chargui", "Hodh El Gharbi", "Inchiri", "Nouakchott Nord", "Nouakchott Ouest", "Nouakchott Sud", "Tagant", "Tiris Zemmour", "Trarza"]},
  {"code": "MU", "name": "Mauritius", "regions": ["Agalega Islands", "Beau Bassin-Rose Hill", "Black River", "Cargados Carajos Shoals", "Curepipe", "Flacq", "Grand Port", "Moka", "Pamplemousses", "Plaines Wilhems", "Port Louis", "Port Louis (City)", "Riviere du Rempart", "Rodrigues Island", "Savanne", "Vacoas-Phoenix"]},
  {"code": "MA", "name": "Morocco", "regions": ["Béni Mellal-Khénifra", "Casablanca-Settat", "Dakhla-Oued Ed-Dahab", "Drâa-Tafilalet", "Fès-Meknès", "Guelmim-Oued Noun", "L'Oriental", "Laâyoune-Sakia El Hamra", "Marrakech-Safi", "Rabat-Salé-Kénitra", "Souss-Massa", "Tanger-Tétouan-Al Hoceïma"]},
  {"code": "MZ", "name": "Mozambique", "regions": ["Cabo Delgado", "Gaza", "Inhambane", "Manica", "Maputo", "Maputo (City)", "Nampula", "Niassa", "Sofala", "Tete", "Zambezia"]},
  {"code": "NA", "name": "Namibia", "regions": ["Erongo", "Hardap", "Karas", "Kavango East", "Kavango West", "Khomas", "Kunene", "Ohangwena", "Omaheke", "Omusati", "Oshana", "Oshikoto", "Otjozondjupa", "Zambezi"]},
  {"code": "NE", "name": "Niger", "regions": ["Agadez", "Diffa", "Dosso", "Maradi", "Niamey", "Tahoua", "Tillabéri", "Zinder"]},
  {"code": "NG", "name": "Nigeria", "regions": ["Abia", "Abuja Federal Capital Territory", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", "Bayelsa", "Benue", "Borno", "Cross River", "Delta", "Ebonyi", "Edo", "Ekiti", "Enugu", "Gombe", "Imo", "Jigawa", "Kaduna", "Kano", "Katsina", "Kebbi", "Kogi", "Kwara", "Lagos", "Nasarawa", "Niger", "Ogun", "Ondo", "Osun", "Oyo", "Plateau", "Rivers", "Sokoto", "Taraba", "Yobe", "Zamfara"]},
  {"code": "CG", "name": "Republic of the Congo", "regions": ["Bouenza", "Brazzaville", "Cuvette", "Cuvette-Ouest", "Kouilou", "Likouala", "Lékoumou", "Niari", "Plateaux", "Pointe-Noire", "Pool", "Sangha"]},
  {"code": "RW", "name": "Rwanda", "regions": ["Eastern", "Kigali", "Northern", "Southern", "Western"]},
  {"code": "SN", "name": "Senegal", "regions": ["Dakar", "Diourbel", "Fatick", "Kaffrine", "Kaolack", "Kedougou", "Kolda", "Louga", "Matam", "Saint-Louis", "Sedhiou", "Tambacounda", "Thies", "Ziguinchor"]},
  {"code": "SC", "name": "Seychelles", "regions": ["Anse Boileau", "Anse Etoile", "Anse Royale", "Anse aux Pins", "Anu Cap", "Baie Lazare", "Baie Sainte Anne", "Beau Vallon", "Bel Air", "Bel Ombre", "Cascade", "Glacis", "Grand'Anse Mahe", "Grand'Anse Praslin", "La Digue", "La Riviere Anglaise", "Les Mamelles", "Mont Buxton", "Mont Fleuri", "Plaisance", "Pointe La Rue", "Port Glaud", "Roche Caiman", "Saint Louis", "Takamaka"]},
  {"code": "SL", "name": "Sierra Leone", "regions": ["Eastern", "Northern", "Southern", "Western"]},
  {"code": "SO", "name": "Somalia", "regions": ["Awdal", "Bakool", "Banaadir", "Bari", "Bay", "Galguduud", "Gedo", "Hiiraan", "Jubbada Dhexe", "Jubbada Hoose", "Mudug", "Nugaal", "Sanaag", "Shabeellaha Dhexe", "Shabeellaha Hoose", "Sool", "Togdheer", "Woqooyi Galbeed"]},
  {"code": "ZA", "name": "South Africa", "regions": ["Eastern Cape", "Free State", "Gauteng", "KwaZulu-Natal", "Limpopo", "Mpumalanga", "North West", "Northern Cape", "Western Cape"]},
  {"code": "SS", "name": "South Sudan", "regions": ["Central Equatoria", "Eastern Equatoria", "Jonglei", "Lakes", "Northern Bahr el Ghazal", "Unity", "Upper Nile", "Warrap", "Western Bahr el Ghazal", "Western Equatoria"]},
  {"code": "SD", "name": "Sudan", "regions": ["Al Bahr al Ahmar", "Al Jazirah", "Al Khartum", "Al Qadarif", "An Nil al Abyad", "An Nil al Azraq", "Ash Shamaliyah", "Gharb Darfur", "Gharb Kurdufan", "Janub Darfur", "Janub Kurdufan", "Kassala", "Nahr an Nil", "Shamal Darfur", "Sharq Darfur", "Shiamal Kurdufan", "Sinnar", "Wasat Darfur Zalinjay"]},
  {"code": "ST", "name": "São Tomé and Príncipe", "regions": ["Principe", "Sao Tome"]},
  {"code": "TZ", "name": "Tanzania", "regions": ["Arusha", "Coast", "Dar es Salaam", "Dodoma", "Iringa", "Kagera", "Kigoma", "Kilimanjaro", "Lindi", "Manyara", "Mara", "Mbeya", "Morogoro", "Mtwara", "Mwanza", "Pemba North", "Pemba South", "Rukwa", "Ruvuma", "Shinyanga", "Singida", "Tabora", "Tanga", "Zanzibar Central/South", "Zanzibar North", "Zanzibar Urban/West"]},
  {"code": "GM", "name": "The Gambia", "regions": ["Banjul", "Central River", "Lower River", "North Bank", "Upper River", "Western"]},
  {"code": "TG", "name": "Togo", "regions": ["Centre", "Kara", "Maritime", "Plateaux", "Savannes"]},
  {"code": "TN", "name": "Tunisia", "regions": ["Ariana", "Beja", "Ben Arous", "Bizerte", "Gabes", "Gafsa", "Jendouba", "Kairouan", "Kasserine", "Kebili", "Kef", "Mahdia", "Medenine", "Monastir", "Nabeul", "Sfax", "Sidi Bouzid", "Siliana", "Sousse", "Tataouine", "Tozeur", "Tunis", "Zaghouan"]},
  {"code": "UG", "name": "Uganda", "regions": ["Abim", "Adjumani", "Amolatar", "Amuria", "Amuru", "Apac", "Arua", "Budaka", "Bududa", "Bugiri", "Bukedea", "Bukwa", "Buliisa", "Bundibugyo", "Bushenyi", "Busia", "Butaleja", "Dokolo", "Gulu", "Hoima", "Ibanda", "Iganga", "Isingiro", "Jinja", "Kaabong", "Kabale", "Kabarole", "Kaberamaido", "Kalangala", "Kaliro", "Kampala", "Kamuli", "Kamwenge", "Kanungu", "Kapchorwa", "Kasese", "Katakwi", "Kayunga", "Kibaale", "Kiboga", "Kiruhura", "Kisoro", "Kitgum", "Koboko", "Kotido", "Kumi", "Kyenjojo", "Lira", "Luuka", "Luwero", "Lyantonde", "Manafwa", "Maracha", "Masaka", "Masindi", "Mayuge", "Mbale", "Mbarara", "Mityana", "Moroto", "Moyo", "Mpigi", "Mubende", "Mukono", "Nakapiripirit", "Nakaseke", "Nakasongola", "Namutumba", "Nebbi", "Ntungamo", "Oyam", "Pader", "Pallisa", "Rakai", "Rukungiri", "Sembabule", "Sironko", "Soroti", "Tororo", "Wakiso", "Yumbe"]},
  {"code": "ZM", "name": "Zambia", "regions": ["Central", "Copperbelt", "Eastern", "Luapula", "Lusaka", "Muchinga", "North-Western", "Northern", "Southern", "Western"]},
  {"code": "ZW", "name": "Zimbabwe", "regions": ["Bulawayo", "Harare", "Manicaland", "Mashonaland Central", "Mashonaland East", "Mashonaland West", "Masvingo", "Matabeleland North", "Matabeleland South", "Midlands"]},
]

/** Codes are ISO 639-1 where one exists, otherwise ISO 639-3. They match the prompts' language codes. */
export const AFRICAN_LANGUAGES: Language[] = [
  {"code": "ach", "name": "Acholi"},
  {"code": "aa", "name": "Afar"},
  {"code": "af", "name": "Afrikaans"},
  {"code": "ak", "name": "Akan (Twi, Fante)"},
  {"code": "am", "name": "Amharic"},
  {"code": "ar", "name": "Arabic"},
  {"code": "bm", "name": "Bambara"},
  {"code": "bci", "name": "Baoulé"},
  {"code": "bem", "name": "Bemba"},
  {"code": "kea", "name": "Cape Verdean Creole"},
  {"code": "ny", "name": "Chichewa (Nyanja)"},
  {"code": "luo", "name": "Dholuo"},
  {"code": "din", "name": "Dinka"},
  {"code": "dyu", "name": "Dyula"},
  {"code": "efi", "name": "Efik"},
  {"code": "en", "name": "English"},
  {"code": "ee", "name": "Ewe"},
  {"code": "fon", "name": "Fon"},
  {"code": "fr", "name": "French"},
  {"code": "ff", "name": "Fula (Fulfulde)"},
  {"code": "gaa", "name": "Ga"},
  {"code": "ha", "name": "Hausa"},
  {"code": "hz", "name": "Herero"},
  {"code": "ibb", "name": "Ibibio"},
  {"code": "ig", "name": "Igbo"},
  {"code": "xh", "name": "isiXhosa"},
  {"code": "zu", "name": "isiZulu"},
  {"code": "kab", "name": "Kabyle"},
  {"code": "kln", "name": "Kalenjin"},
  {"code": "kam", "name": "Kamba"},
  {"code": "kr", "name": "Kanuri"},
  {"code": "ki", "name": "Kikuyu"},
  {"code": "kmb", "name": "Kimbundu"},
  {"code": "rw", "name": "Kinyarwanda"},
  {"code": "rn", "name": "Kirundi"},
  {"code": "kg", "name": "Kongo"},
  {"code": "kri", "name": "Krio"},
  {"code": "kj", "name": "Kwanyama"},
  {"code": "ln", "name": "Lingala"},
  {"code": "ngl", "name": "Lomwe"},
  {"code": "loz", "name": "Lozi"},
  {"code": "lg", "name": "Luganda"},
  {"code": "lgg", "name": "Lugbara"},
  {"code": "luy", "name": "Luhya"},
  {"code": "xog", "name": "Lusoga"},
  {"code": "mas", "name": "Maasai"},
  {"code": "mg", "name": "Malagasy"},
  {"code": "mfe", "name": "Mauritian Creole"},
  {"code": "men", "name": "Mende"},
  {"code": "mos", "name": "Mooré"},
  {"code": "ng", "name": "Ndonga"},
  {"code": "nd", "name": "Northern Ndebele"},
  {"code": "nus", "name": "Nuer"},
  {"code": "om", "name": "Oromo"},
  {"code": "pt", "name": "Portuguese"},
  {"code": "nyn", "name": "Runyankole"},
  {"code": "sg", "name": "Sango"},
  {"code": "seh", "name": "Sena"},
  {"code": "nso", "name": "Sepedi"},
  {"code": "srr", "name": "Serer"},
  {"code": "st", "name": "Sesotho"},
  {"code": "tn", "name": "Setswana"},
  {"code": "sn", "name": "Shona"},
  {"code": "sid", "name": "Sidamo"},
  {"code": "so", "name": "Somali"},
  {"code": "snk", "name": "Soninke"},
  {"code": "sw", "name": "Swahili"},
  {"code": "ss", "name": "Swati"},
  {"code": "shi", "name": "Tachelhit"},
  {"code": "zgh", "name": "Tamazight"},
  {"code": "tem", "name": "Temne"},
  {"code": "teo", "name": "Teso"},
  {"code": "ti", "name": "Tigrinya"},
  {"code": "tiv", "name": "Tiv"},
  {"code": "toi", "name": "Tonga (Zambia)"},
  {"code": "lua", "name": "Tshiluba"},
  {"code": "ve", "name": "Tshivenda"},
  {"code": "tum", "name": "Tumbuka"},
  {"code": "wal", "name": "Wolaytta"},
  {"code": "wo", "name": "Wolof"},
  {"code": "ts", "name": "Xitsonga"},
  {"code": "yao", "name": "Yao"},
  {"code": "yo", "name": "Yoruba"},
]

const LANGUAGE_NAMES = new Map(AFRICAN_LANGUAGES.map(l => [l.code, l.name]))
export const languageName = (code: string) => LANGUAGE_NAMES.get(code) || code
